databases:
  - name: upload_my_pictures_db
    databaseName: upload_my_pictures
    user: anthonychao
    plan: free

services:
  - type: web
    name: upload_my_pictures
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: upload_my_pictures_db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
